### ISSUE TITLE
Error in spacing calculation for unicode caracters

### ISSUE THREAD

**Issue by xja** [PlainTextTools/plain-text-table#3]
https://imgur.com/a/GVGaiR6 https://i.imgur.com/UaXHK0F.png

**Comment by Japillow** [comment]
This issue could be best renamed : "Error in spacing calculation for unicode caracters"

I have the same issue with this following example due to the ⊆ characters : 
![Github](https://user-images.githubusercontent.com/11227493/95558570-ba888700-0a16-11eb-9e80-dbd31187df07.PNG)

**Comment by xja** [comment]
> This issue could be best renamed : "Error in spacing calculation for unicode caracters"
> 
> I have the same issue with this following example due to the ⊆ characters :
> ![Github](https://user-images.githubusercontent.com/11227493/95558570-ba888700-0a16-11eb-9e80-dbd31187df07.PNG)

thanks for the advice for title. i guess there's no active maintainer anymore.

**Comment by Japillow** [comment]
it seems this issue is due to the use of UTF-8 for which complex unicode caracters are not fixed-case, whereas it's the case for UTF-16 and UTF-32

**Comment by phuclv90** [comment]
> it seems this issue is due to the use of UTF-8 for which complex unicode caracters are not fixed-case, whereas it's the case for UTF-16 and UTF-32

it has nothing to do with UTF-8, 16 or 32. They're just different **encodings** that map a series of bytes to a number in the Unicode charset (which represents a glyph). The difference in width is due to the glyph after rendering doesn't have the same widths. You need a good monospaced font and an excellent renderer which probably didn't exist

**Comment by xja** [comment]
> > it seems this issue is due to the use of UTF-8 for which complex unicode caracters are not fixed-case, whereas it's the case for UTF-16 and UTF-32
> 
> it has nothing to do with UTF-8, 16 or 32. They're just different **encodings** that map a series of bytes to a number in the Unicode charset (which represents a glyph). The difference in width is due to the glyph after rendering doesn't have the same widths. You need a good monospaced font and an excellent renderer which probably didn't exist

yeah, monospace font, that idea did came to me earlier as well, i guess it's the best solution for now
